Makefile
Prow said timeout was hit.
Let's increase this to 30m and see if that fixes the error.
=> increase timeout for golang ci

.gitignore, README.md, hack/run-locally.sh
This PR creates a script so we can hack on the operator locally.
1. make
1. `oc apply -f deploy/`
1. `oc apply -f deploy/crd`
1. `hack/run-locally.sh`
1. Optionally run `oc apply -f deploy/examples/job.yaml`
=> add run-locally script

pkg/operator/target_config_reconciler.go
I wanted to follow a similar pattern that lws-operator did.
1) Compute owner referneces once and pass that information into all objects that Kueue manages.
2) Webhooks must be before the deployment.
3) Namespaced resources will store the resource version in the deployment annotations.
We don't need that information for cluster wide resources.
=> Refactors of the main reconcile loop

fbc/v4.18/Containerfile.catalog, fbc/v4.18/catalog-template.yaml, fbc/v4.18/catalog/catalog.json
This just creates the basic files for an FBC for one version.  THis will need to be flushed out with additional options and duplicated to support additional OCP versions
Part of [OCPNODE-3045](https://issues.redhat.com//browse/OCPNODE-3045)
=> generate required files for basic fbc

.tekton/kueue-bundle-pull-request.yaml, .tekton/kueue-fbc-418-pull-request.yaml, .tekton/kueue-operator-pull-request.yaml
This should only run bundle jobs on changes to bundle files, fbc jobs on changes to fbc files, and operator jobs on all other changes.  Testing is a bit tricky as there are many combinations of changes that need to work and this PR only covers one.  All jobs are running as expected since files for all three images changed.  The plan would be to merge and then check other PRs and make sure the right jobs are running.  If not we fix them or just revert this.
=> use CEL expression to limit fbc konflux jobs to just changes to fbc

pkg/configmap/configmap.go, pkg/configmap/configmap_test.go
This is required to avoid seeing this issue in the kueue-controller-manager logs:
```sh
{"level":"error","ts":"2025-04-10T20:32:54.80835478Z","logger":"controller-runtime.source.EventHandler","caller":"source/kind.go:71","msg":"if kind is a CRD, it should be installed before calling Start","kind":"Cohort.kueue.x-k8s.io","error":"no matches for kind \"Cohort\" in version \"kueue.x-k8s.io/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind[...]).Start.func1.1\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/source/kind.go:71\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/loop.go:87\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext\n\t/workspace/vendor/k8s.io/a …
```
=> pkg: disable HierarchialCohorts featuregate

.tekton/kueue-bundle-pull-request.yaml, .tekton/kueue-fbc-418-pull-request.yaml, .tekton/kueue-operator-pull-request.yaml
This change replaces the solution in PR #165. Too many complications with using separate annotations (on-path-change, on-path-change-ignore are incompatible with on-cel-expression).  The only solution is to use on-cel-expression with complicated logic.  Again, this looks like it works on this PR, but will need to check other PRs to make sure the right jobs are running.
=> use on-cel-expression to filter file changes

bundle/manifests/kueue-operator.clusterserviceversion.yaml
We have to use prod repos since that is what will ship.  Internal testing will require the use of a mirror set to point prod repos to quay repos.
=> use prod repos in CSV

Makefile, bundle/manifests/kueue-operator.clusterserviceversion.yaml, hack/preserve-bundle-labels.sh
Bundle generation process was adding the wrong image urls for the operator and operand.  These must be the prod repos (registry.redhat.io) and use digests.  This is required because the bundle is not rebuilt on release.  A consequence of this is that you need to use a mirror set to test with the bundle.
=> add operator image back to csv

Makefile, must-gather/Dockerfile, must-gather/collection-scripts/gather, must-gather/collection-scripts/gather-kueue
=> Custom must gather image

Dockerfile, Makefile, bundle.Dockerfile, bundle/manifests/kueue-operator.clusterserviceversion.yaml, hack/preserve-bundle-labels.sh
Updated the kueue digest with the last pushed to prod.  I also has to modify the scripts that generate the CSV so it is consistent.  Found a number of places the version needed to be bumped to be consistent.
=> update kueue image; bump version to 0.1.0

.tekton/kueue-fbc-418-pull-request.yaml, .tekton/kueue-operator-pull-request.yaml
This is temporary until we move FBCs to their own repo, but still need to limit extra operator builds to eliminate extra nudges.
=> tweak cel expression for FBCs

fbc/v4.18/catalog-template.yaml, fbc/v4.18/catalog/kueue-operator/catalog.json, fbc/v4.19/Containerfile.catalog, fbc/v4.19/catalog-template.yaml, fbc/v4.19/catalog/kueue-operator/catalog.json
=> update fbcs with TP bundles

bundle/manifests/kueue-operator.clusterserviceversion.yaml
no nudge happened for the kueue image.  Manually updating the digests for the latest build.
=> update kueue digest in CSV to latest

pkg/configmap/configmap.go, pkg/configmap/configmap_test.go
kueue v0.11.5 changed the name of this feature gate to fix a typo.
We need to change this feature gate as it is causing kueue to not install when using latest patch from 0.11.5.
=> fix typo in HierarchicalCohorts feature gate

pkg/configmap/configmap.go, pkg/configmap/configmap_test.go, test/e2e/e2e_operator_test.go
When using `labelPolicy` with `None` value, the `managedJobsWithoutQueueName` is enabled, consequently any job that doesn't have the kueue label set will still be managed by Kueue. To reduce the scope of affected jobs this commits set the `ManagedJobsNamespaceSelector` to only select the namespaces with label `kueue.openshift.io/managed=true`.
=> OCPNODE-3306: Add `ManagedJobsNamespaceSelector` to Kueue configuration

Makefile
Must gather was only running when the e2e test ran successfully.
We want to run must gather on all runs so we can triage failure.
=> run must gather even on failure

Makefile, test/e2e/e2e_suite_test.go
As we're using the bundle for the e2e tests we don't need to set the `OPERATOR_IMAGE` and `KUEUE_IMAGE` anymore.
=> Remove unecessary env vars from e2e tests

test/e2e/e2e_operator_test.go, test/e2e/testutils/builders.go
This change prevents conflicts when both Deployments and StatefulSets exist in the same namespace and ensures tests can reliably identify the correct Pods. It also fixes the issue where the Stateful workload lacked the kueue.x-k8s.io/job-uid label that the test was looking for—instead, it now uses an ownerReferences field that points to the Pod.
=> test/e2e: address e2e test failure for statefulset

Makefile
This PR removes the specification of KUEUE_IMAGE and OPERATOR_IMAGE env vars.
It also moves the dependency of setting up the must-gather image  to the target that needs it.
=> Clean up e2e targets in Makefile

Makefile
If we run undeploy-ocp after each test suite,
we would get kueue assets removed and if another
test suite attempts to run, it would fail. Also,
in CI there is one specific post step to get the
must-gather, so we don't need to run it on each test target. This commit removed the undeploy-ocp and must-gather from the test targets that run on CI.
=> Clean up e2e targets

test/e2e/testutils/builders.go, test/e2e/testutils/utils.go
I was hitting this issue while running the e2e testsuite in a disconnected cluster.
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/66357/rehearse-66357-pull-ci-openshift-kueue-operator-release-1.0-test-e2e-disconnected/1942404961056854016/artifacts/test-e2e-disconnected/e2e-kueue/build-log.txt
The pod was in a pending state bc it was trying to pull the image from internet.
=> test: use internal registry image for disconnected clusters

test/e2e/e2e_operator_test.go, test/e2e/e2e_suite_test.go, test/e2e/testutils/client.go, test/e2e/testutils/utils.go
Even though we already have a destroy of namespace
where k8s assets are created, there is not wait for
all the assets to be properly cleaned up. After triggering
deletion of namespace we already proceed to the next
test scenario which is of deleting Kueue instance.
This can leave some CRDs behind if some k8s assets
were not yet fully cleaned up, and even when we recreate
the Kueue instance in the following test scenario,
this CRD will eventually get deleted.
This commit adds defer clean ups to assets generated
in the e2e test to ensure no leftovers are left by the
OCP e2e suite that could affect other suites that run after it.
=> OCPNODE-3449: Remove assets generated during the e2e test

pkg/operator/target_config_reconciler.go
We shouldn't be deleting cluster roles
that are meant for the operator and not
the operand, even if they get recreated.
This commit fixes the issue by skipping
the clean up of any cluster role that
has openshift.io in the name.
=> Fix clusterRole clean up

Makefile, bundle/manifests/kueue-operator.clusterserviceversion.yaml
This commit manually syncs the operator image in the bundle
to make sure our periodic jobs use the latest operator code
avaialable. This fix is needed while we work on identifying
what is wrong with the nudges. It also removes an unnecessary
file that is created when generating the bundle.
=> Manually sync operator image in the Bundle

Makefile
In CI we will be running deployment of cert-manager in a separate step, so we don't need to run it twice when running the OCP and upstream e2e tests.
=> Remove the deployment of cert-manager from e2e makefile targets

renovate.json
Use regexp to catch Dockerfile.* and Dockerfile.
=> fix auto merge for dockerfiles

Makefile, README.md, bundle.Dockerfile, bundle/manifests/kueue-operator.clusterserviceversion.yaml, hack/preserve-bundle-labels.sh
To prepare for the 1.0.1, let's bump the operator version.
=> OCPNODE-3486: Bump operator version for 1.0.1 release

hack/wait-for-kueue-leader-election.sh
We have a flake in our CI with lease detection. `oc logs deployment` will grab the first pod and gets its logs.
Sometimes that pod gets the lease while other times a different pod gets the lease.
We will grab all the logs on all pods for this deployment and search for lease acquired.
ex:
```  
kubectl logs deployment/nginx --all-pods=true
```
=> use all-pods for oc logs deployment

related_images.developer.json
This PR updates the related_images.developer.json file to use the Konflux component names and their latest hashes. We should get nudge bumps after this PR since the component names line up.
=> related_images: use the latest images and use the latest hashes

.tekton/kueue-bundle-main-pull-request.yaml, .tekton/kueue-bundle-main-push.yaml, .tekton/kueue-must-gather-main-pull-request.yaml, .tekton/kueue-must-gather-main-push.yaml, .tekton/kueue-operator-main-pull-request.yaml, .tekton/kueue-operator-main-push.yaml
Title ^ :) 
Also adds related_images.json to the cel expression of the bundle tekton files.
We also do not want the operator to rebuild on related_images.*.json updates (infinite konflux loop). I added the files to the 'ignore' list.
=> add architectures to must-gather image and tweak cel expressions

.gitmodules, .snyk, README.md, bindata/assets/kueue-operator/crds/crd-admissionchecks.kueue.x-k8s.io.yaml, bindata/assets/kueue-operator/crds/crd-clusterqueues.kueue.x-k8s.io.yaml, bindata/assets/kueue-operator/crds/crd-cohorts.kueue.x-k8s.io.yaml, bindata/assets/kueue-operator/crds/crd-localqueues.kueue.x-k8s.io.yaml, bindata/assets/kueue-operator/crds/crd-multikueueclusters.kueue.x-k8s.io.yaml, bindata/assets/kueue-operator/crds/crd-multikueueconfigs.kueue.x-k8s.io.yaml, bindata/assets/kueue-operator/crds/crd-provisioningrequestconfigs.kueue.x-k8s.io.yaml, bindata/assets/kueue-operator/crds/crd-resourceflavors.kueue.x-k8s.io.yaml, bindata/assets/kueue-operator/crds/crd-topologies.kueue.x-k8s.io.yaml, bindata/assets/kueue-operator/crds/crd-workloadpriorityclasses.kueue.x-k8s.io.yaml, bindata/assets/kueue-operator/crds/crd-workloads.kueue.x-k8s.io.yaml, bindata/assets/kueue-operator/validatingwebhook.yaml, hack/run-locally.sh, hack/sync_manifests.py, renovate.json
* Bumps the upstream gitsubmodule to track the upstream main branch
* Changes hack/sync_manifests.py to have a main function and supports (optionally) syncing manifests from the gitsubmdule
* Syncs the CRDs from the upstream main branch
* Updates the README with new functionality
* Changes renovate git submodule update to run only on Tuesdays. This will prevent churn everyday with upstream changes.
=> bumps main to upstream main branch (what will be 0.14)

pkg/operator/target_config_reconciler.go, test/e2e/e2e_operator_test.go
We shouldn't be deleting clusterRoles that are created with the bundle when the kueue instance is deleted. Otherwise, when the kueue instance is created again this clusterrole won't be present anymore.
=> Do not remove clusterRole created by the bundle
