openshift/kueue-operator

go.mod, go.sum, vendor/golang.org/x/net/html/doc.go, vendor/golang.org/x/net/html/doctype.go, vendor/golang.org/x/net/html/foreign.go, vendor/golang.org/x/net/html/iter.go, vendor/golang.org/x/net/html/node.go, vendor/golang.org/x/net/html/parse.go, vendor/golang.org/x/net/http2/client_conn_pool.go, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/http2.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/transport.go, vendor/golang.org/x/net/http2/unencrypted.go, vendor/modules.txt
Fix scanner issues with golang net by upgrading transitive dependency to 0.33
=> update golang net to 0.33

config/schemapatch/operator.openshift.io_kueues.yaml, deploy/crd/kueue-operator.crd.yaml, manifests/operator.openshift.io_kueues.yaml, pkg/apis/kueueoperator/v1alpha1/types.go
Ran Kal linter on the api and fixed errors.
=> run kal linter on kueue-operator api

.golangci.yml, Makefile, pkg/operator/starter.go, pkg/operator/target_config_reconciler.go
1) Add make target for lint
2) Fix lint issues
I will add a lint step to openshift/release also.
=> add golang-ci to operator

pkg/operator/target_config_reconciler.go
Fix error where deployment, pod and statefulsets were still being used.
=> fix webhook bug where deployment, pod and statefulset were not dropped

Makefile, test/e2e/bindata/assets/00_kueue-operator.crd.yaml
1) Add a step to copy the latest CRD code to our e2e tests.
=> Sync crd to test

Makefile
This hopefully fixes o/release problem for running `make generate`.
=> install via mod flag for ginkgo and controller-gen

.tekton/kueue-bundle-pull-request.yaml, .tekton/kueue-bundle-push.yaml, .tekton/kueue-operator-pull-request.yaml, .tekton/kueue-operator-push.yaml
ref: https://issues.redhat.com/browse/KFLUXSPRT-2167
Trying to increase memory limits to hopefully avoid OOMKills.
=> bump up memory limits for sast-coverity check

Dockerfile, bundle.Dockerfile
Build konflux PR on latest main to fix CI failures.
=> rebase repo and add docker files

pkg/operator/target_config_reconciler.go, test/e2e/e2e_operator_test.go
=> OCPNODE-3007: Do not install alpha crd by default

renovate.json
Seeing docs in Konflux this supposely will allow us to checkbox the rebase box and force rebases.
=> add renovate config to hopefully allow for rebasing of PRs

Makefile, hack/replace-image.sh, hack/revert-deploy-files.sh, hack/update-deploy-files.sh
One place to create images. `make operator-build`
=> remove `make images` since we use operator-build

pkg/operator/target_config_reconciler.go
This fixes the current CI failure
```sh
{"level":"error","ts":"2025-03-29T03:54:45.652276618Z","logger":"setup","caller":"kueue/main.go:171","msg":"Unable to initialize metrics certificate watcher","error":"open /etc/kueue/metrics/certs/tls.crt: no such file or directory","stacktrace":"main.main\n\t/workspace/cmd/kueue/main.go:171\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:272"}
```
=> pkg: add metrics certificates

bundle/manifests/kueue-operator.clusterserviceversion.yaml
Add operator image for relatedImages.
=> add operator image to csv.

.tekton/kueue-bundle-1-0-pull-request.yaml, .tekton/kueue-bundle-1-0-push.yaml, .tekton/kueue-fbc-418-pull-request.yaml, .tekton/kueue-fbc-418-push.yaml, .tekton/kueue-operator-1-0-pull-request.yaml, .tekton/kueue-operator-1-0-push.yaml
https://github.com/openshift/kueue-operator/commit/ddf38a8d8f1a64b3d9383f72fff7d905b41fdc80
=> Manually konflux bump release 1.0

Makefile
I ran these targets locally and both tests look fine.
=> Makefile: add e2e targets for prow CI

bundle/manifests/kueue-operator.clusterserviceversion.yaml
This points the image urls for the operator and operand to the versioned images.
=> Update to versioned  imageurls

renovate.json
=> fix renovate configuration issue

Makefile
Make doesn't recognize `$`.  We need to escape `$` characters with another `$`.
$$$$4 becomes $$4 after Make's first parsing layer. The shell then sees awk '{print $4}' as intended.
=> Makefile: refactor e2e Makefile targets

bundle/manifests/kueue-operator.clusterserviceversion.yaml
=> [release-1.0] use prod repos in CSV

renovate.json
I think this will add basebranch to the end of the PRs from renovate.
=> add basebranch name as suffix to the renovate PR titles

.tekton/kueue-must-gather-pull-request.yaml, .tekton/kueue-must-gather-push.yaml
=> Add correct Dockerfile path

.tekton/kueue-bundle-1-0-pull-request.yaml, .tekton/kueue-fbc-418-pull-request.yaml, .tekton/kueue-operator-1-0-pull-request.yaml
Already updated main, but this will eliminate the redundant builds that are causing circular nudges.
=> change cel expression to eliminate redundant builds

Makefile
=> Remove duplicate test targets

.tekton/kueue-must-gather-1-0-pull-request.yaml, .tekton/kueue-must-gather-1-0-push.yaml
=> Add cel-on-expression files filters

.tekton/kueue-bundle-pull-request.yaml, .tekton/kueue-bundle-push.yaml, .tekton/kueue-fbc-418-push.yaml, .tekton/kueue-operator-pull-request.yaml, .tekton/kueue-operator-push.yaml
Equivalent changes as PR #306.  All to eliminate circular nudges.
=> add cel-on-expression files filters to push  pipelins

.tekton/kueue-must-gather-1-0-pull-request.yaml, .tekton/kueue-must-gather-1-0-push.yaml, must-gather/Dockerfile
enable hermetic and source-image-build
Add required labels to containerfile
=> Fix ec for must gather

Makefile
=> Correct the must-gather image name

must-gather/Dockerfile
=> Correct must-gather dockerfile

pkg/operator/target_config_reconciler.go
=> NO-JIRA: Fix deletion of Kueue CR

Makefile, bundle.Dockerfile, bundle/manifests/kueue-operator.clusterserviceversion.yaml, hack/preserve-bundle-labels.sh
We have breaking changes.
Promoting API to v1 and renaming groupName.
Due to this, we are releasing a new minor version for TP.
=> update bundle to 0.2.0 for tp

OWNERS
cc @sohankunkerkar @MaysaMacedo @PannagaRao
=> add mayasa and pannaga as owners to kueue operator repo

Makefile, bundle.Dockerfile, hack/preserve-bundle-labels.sh
Update release version to 1.1 and use main images for e2e.
=> OCPNODE-3537: use main kueue for operator e2e

.gitmodules, .snyk, Makefile, renovate.json
tracks the 0.12 branch in upstream/kueue/src
=> add kueue gitsubmodule

test/e2e/e2e_local_queue_defaulting_test.go, test/e2e/e2e_operator_test.go, test/e2e/testutils/constants.go, test/e2e/testutils/utils.go
This PR adds the following testing scenarios for `LocalQueueDefaulting`:
- Check if `LocalQueueDefaulting` is creating the expected Labels
- Check if `LocalQueueDefaulting` works with other LocalQueues
=> Local queue default tests

.tekton/kueue-must-gather-1-1-pull-request.yaml, .tekton/kueue-must-gather-1-1-push.yaml, .tekton/kueue-operator-1-1-pull-request.yaml, .tekton/kueue-operator-1-1-push.yaml
MULTIARCH-5625: Adding support for ppc64le for kueue-operator on release-0.12
=> MULTIARCH-5625: Adding support for ppc64le for kueue-operator on release-1.1

README.md
Fixes up the readme with a typo on the submodule location.
=> fixup readme for submodule

bundle/manifests/kueue-operator.clusterserviceversion.yaml, deploy/base-csv/kueue-operator.clusterserviceversion.yaml, deploy/examples/job.yaml
Console team suggested we remove the "namespace" line in our CSV to avoid OCPBUGS-58118
=> remove "namespace" from CR example file and rendered CSV

Makefile, upstream/kueue/e2e-test-ocp.sh, upstream/kueue/patch/README.md, upstream/kueue/patch/e2e.patch
Stop using kueue fork and use submodules
=> OCPKUEUE-280: Enable e2e from submodules
